# Regenerate the in-repo "station-level per-trip crash risk" map shipped at
# static/figures/citibike-station-risk.html.
#
# Source: scripts/data/citibike_station_risk.json — the real CitiBike station
# coordinates + risk tiers, committed in-repo (extracted from the station-risk
# analysis) so the Work figure needs no external host. Each dot is one station;
# the warm-charcoal dots recede and amber flags the highest-risk stations, in
# the site's single-accent palette (vs. the old external green/orange/red map).
#
# Run:  python scripts/gen_citibike_fig.py
#
import json, os, math

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data", "citibike_station_risk.json")
OUT = os.path.join(HERE, "..", "static", "figures", "citibike-station-risk.html")

# Per-tier dot radius (user units) — risk reads as size + colour together.
RADIUS = {0: 1.3, 1: 1.7, 2: 2.1, 3: 2.7}

VB_H = 600.0          # viewBox height; width derives from the data aspect
PAD = 18.0            # inner padding (user units)


def project(points):
    lats = [p[0] for p in points]
    lngs = [p[1] for p in points]
    lat0 = sum(lats) / len(lats)
    kx = math.cos(math.radians(lat0))           # equirectangular x correction
    lat_min, lat_max = min(lats), max(lats)
    lng_min, lng_max = min(lngs), max(lngs)
    xr = (lng_max - lng_min) * kx
    yr = (lat_max - lat_min)
    aspect = xr / yr
    vb_w = VB_H * aspect
    sx = (vb_w - 2 * PAD) / xr
    sy = (VB_H - 2 * PAD) / yr
    out = []
    for lat, lng, t in points:
        x = PAD + (lng - lng_min) * kx * sx
        y = PAD + (lat_max - lat) * sy           # north up
        out.append((x, y, t))
    return out, vb_w


def main():
    blob = json.load(open(DATA))
    pts, vb_w = project(blob["points"])
    # Draw low -> very_high (data is pre-sorted) so amber sits on top.
    circles = "".join(
        f'<circle cx="{x:.1f}" cy="{y:.1f}" r="{RADIUS[t]}" class="t{t}"/>'
        for (x, y, t) in pts
    )
    n = len(pts)
    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>CitiBike — station-level per-trip crash risk</title>
<!-- GENERATED by scripts/gen_citibike_fig.py from scripts/data/citibike_station_risk.json.
     Canonical warm-charcoal + amber tokens come from static/figures/_palette.css;
     dots recede in --ink and the highest-risk stations flag in --amber. -->
<link rel="stylesheet" href="/figures/_palette.css" />
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&display=swap');
  :root {{ --dim:#6d6757; }}
  @media (prefers-color-scheme:dark){{ :root{{ --dim:#8a8370; }} }}
  :root[data-theme="light"]{{ --dim:#6d6757; }}
  :root[data-theme="dark"]{{ --dim:#8a8370; }}
  html,body{{margin:0;background:var(--emb-bg);font-family:'JetBrains Mono',ui-monospace,monospace}}
  .wrap{{display:flex;flex-direction:column;height:100vh;box-sizing:border-box;
        padding:14px 18px;gap:8px}}
  .bar{{display:flex;justify-content:space-between;align-items:baseline;
       font-size:11px;letter-spacing:0.08em;text-transform:uppercase;color:var(--dim)}}
  .bar .tag{{border:1px solid var(--line);border-radius:5px;padding:1px 7px}}
  .map{{flex:1;min-height:0;width:100%}}
  .map svg{{width:100%;height:100%;display:block}}
  /* Risk reads as colour + size: low/medium recede in ink, high/very_high flag amber. */
  circle{{stroke:none}}
  .t0{{fill:var(--ink);fill-opacity:.24}}
  .t1{{fill:var(--ink);fill-opacity:.5}}
  .t2{{fill:var(--amber);fill-opacity:.66}}
  .t3{{fill:var(--amber);fill-opacity:1}}
</style>
</head>
<body>
<div class="wrap">
  <div class="bar"><span>stations &middot; per-trip crash risk</span><span class="tag">{n:,} stations</span></div>
  <div class="map">
    <svg viewBox="0 0 {vb_w:.1f} {VB_H:.0f}" role="img"
         aria-label="Map of {n:,} CitiBike stations across New York, each a dot coloured by exposure-adjusted per-trip crash risk; the highest-risk stations are amber."
         preserveAspectRatio="xMidYMid meet">
      {circles}
    </svg>
  </div>
</div>
<!-- Figure embed channel: theme sync + ready handshake (see /figures/_embed.js). -->
<script src="/figures/_embed.js"></script>
</body>
</html>
"""
    with open(OUT, "w") as f:
        f.write(html)
    print(f"wrote {os.path.relpath(OUT, os.path.join(HERE, '..'))}  ({n} stations, {len(html)//1024} KB, viewBox {vb_w:.0f}x{int(VB_H)})")


if __name__ == "__main__":
    main()
