# Regenerate the in-repo, interactive "station-level per-trip crash risk" map
# shipped at static/figures/citibike-station-risk.html.
#
# Source: scripts/data/citibike_station_risk.json — the real CitiBike stations
# ([lat, lng, tier, risk, name]), committed in-repo so the Work figure needs no
# external host. The figure is an interactive Leaflet map (pan / zoom / popups)
# on a theme-matched minimal CartoDB basemap; stations recede in --ink and the
# highest-risk stations flag in --amber, recoloured live with the site theme.
#
# Run:  python scripts/gen_citibike_fig.py
#
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, "data", "citibike_station_risk.json")
OUT = os.path.join(HERE, "..", "static", "figures", "citibike-station-risk.html")


def main():
    blob = json.load(open(DATA, encoding="utf-8"))
    stations = blob["stations"]
    n = len(stations)
    data_js = json.dumps(stations, ensure_ascii=False, separators=(",", ":"))

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>CitiBike — station-level per-trip crash risk</title>
<!-- GENERATED by scripts/gen_citibike_fig.py from scripts/data/citibike_station_risk.json.
     Interactive Leaflet map; warm-charcoal + amber tokens from _palette.css drive the
     markers, and the CartoDB basemap swaps with the site theme. -->
<link rel="stylesheet" href="/figures/_palette.css" />
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.css" />
<script src="https://cdn.jsdelivr.net/npm/leaflet@1.9.4/dist/leaflet.js"></script>
<style>
  @import url('https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500;600&display=swap');
  html,body{{margin:0;height:100%;background:var(--emb-bg);
            font-family:'JetBrains Mono',ui-monospace,monospace}}
  #map{{position:absolute;inset:0;background:var(--emb-bg)}}
  /* Let the markers carry the eye while the basemap gives quiet geographic context. */
  .leaflet-tile-pane{{opacity:0.92}}
  .leaflet-container{{background:var(--emb-bg);font-family:inherit}}
  .leaflet-control-zoom a{{
    background:var(--emb-bg);color:var(--ink);border-color:var(--line);
    font-weight:600;font-family:inherit}}
  .leaflet-control-zoom a:hover{{color:var(--amber)}}
  .leaflet-bar{{box-shadow:none;border:1px solid var(--line)}}
  /* Popup styled to the palette. */
  .leaflet-popup-content-wrapper{{
    background:var(--emb-bg);color:var(--ink);border:1px solid var(--line);
    border-radius:6px;box-shadow:none}}
  .leaflet-popup-tip{{background:var(--emb-bg);border:1px solid var(--line)}}
  .leaflet-popup-content{{margin:8px 11px;font-size:11.5px;line-height:1.5}}
  .pop-name{{font-weight:600;color:var(--ink)}}
  .pop-tier{{color:var(--amber);text-transform:uppercase;letter-spacing:0.04em;
            font-size:10.5px}}
  .pop-risk{{color:var(--ink);opacity:0.7}}
  .leaflet-control-attribution{{
    background:transparent;color:var(--ink);opacity:0.5;font-size:9px}}
  .leaflet-control-attribution a{{color:var(--ink)}}
</style>
</head>
<body>
<div id="map" role="application"
     aria-label="Interactive map of {n:,} CitiBike stations across New York; each dot is a station coloured by exposure-adjusted per-trip crash risk, the highest-risk stations in amber."></div>
<script>
  var STATIONS = {data_js};
  var TIERS = ["low","medium","high","very high"];
  // tier -> [radius, fillOpacity, useAmber, strokeWeight]
  var STYLE = [[1.2,0.55,false,0],[1.6,0.7,false,0],[2.1,0.9,true,0],[2.9,1.0,true,0.5]];

  function theme() {{
    var t = document.documentElement.getAttribute("data-theme");
    if (t === "light" || t === "dark") return t;
    return matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
  }}
  function token(name) {{
    return getComputedStyle(document.documentElement).getPropertyValue(name).trim();
  }}

  var map = L.map("map", {{
    preferCanvas: true, scrollWheelZoom: false, attributionControl: true, zoomControl: true
  }});

  // Theme-matched minimal basemap (no labels — the dots are the data).
  function tileUrl(th) {{
    var style = th === "light" ? "light_nolabels" : "dark_nolabels";
    return "https://{{s}}.basemaps.cartocdn.com/rastertiles/" + style + "/{{z}}/{{x}}/{{y}}{{r}}.png";
  }}
  var tiles = L.tileLayer(tileUrl(theme()), {{
    maxZoom: 18, subdomains: "abcd", detectRetina: true,
    attribution: '&copy; OpenStreetMap &copy; CARTO'
  }}).addTo(map);

  var markers = STATIONS.map(function (s) {{
    var st = STYLE[s[2]];
    var m = L.circleMarker([s[0], s[1]], {{ radius: st[0], weight: st[3], opacity: 1 }});
    m.__t = s[2];
    m.bindPopup(
      '<span class="pop-name">' + s[4] + '</span><br>' +
      '<span class="pop-tier">' + TIERS[s[2]] + ' risk</span> ' +
      '<span class="pop-risk">&middot; index ' + s[3] + '</span>'
    );
    return m;
  }});
  var layer = L.layerGroup(markers).addTo(map);
  map.fitBounds(L.latLngBounds(STATIONS.map(function (s) {{ return [s[0], s[1]]; }})).pad(0.04));

  function recolor() {{
    var ink = token("--ink"), amber = token("--amber");
    markers.forEach(function (m) {{
      var st = STYLE[m.__t], c = st[2] ? amber : ink;
      m.setStyle({{ color: c, fillColor: c, fillOpacity: st[1] }});
    }});
  }}
  recolor();

  // React to the embed channel's theme signal (data-theme on <html>).
  new MutationObserver(function () {{
    tiles.setUrl(tileUrl(theme()));
    recolor();
  }}).observe(document.documentElement, {{ attributes: true, attributeFilter: ["data-theme"] }});
</script>
<!-- Figure embed channel: theme sync + ready handshake (see /figures/_embed.js). -->
<script src="/figures/_embed.js"></script>
</body>
</html>
"""
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(html)
    print(f"wrote {os.path.relpath(OUT, os.path.join(HERE, '..'))}  ({n} stations, {len(html)//1024} KB)")


if __name__ == "__main__":
    main()
